---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: practice-cluster
  region: us-east-2
nodeGroups:
  - name: ng-1
    instanceType: t2.small
    desiredCapacity: 1
    volumeSize: 8
    ssh: 
      allow: true
---