apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment_test
  labels: 
    app: deployment
spec:
  minReadySeconds: 3
  replicas: 2 
  selector: 
    matchLabels: 
      app: deployment 
  template: 
    metadata: 
      name : deployment_pod
      labels:
        app: deployment 
    spec: 
      containers: 
        - name: deployment_container
          image: apache:latest 
          ports: 
            - containerPort: 80 
              protocol: TCP 
