---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-test
  labels: 
    app: deployment
spec:
  minReadySeconds: 3
  replicas: 2 
  selector: 
    matchLabels: 
      app: deployment 
  template: 
    metadata: 
      name : deployment-pod
      labels:
        app: deployment 
    spec: 
      containers: 
        - name: deployment-container
          image: apache:latest 
          ports: 
            - containerPort: 80 
              protocol: TCP 
---
apiVersion: v1
kind: Service
metadata:
  name: deployment-svc
spec:
  type: NodePort 
  selector: 
    app: deployment 
  ports: 
    - port: 8080
      nodePort: 30000
      targetPort: 80
---