---
apiVersion: v1
kind: ReplicationController
metadata:
  name: replica-1
  labels:
    app: apache
    version: latest
spec:
  minReadySeconds: 2 # bydefault value '0'
  replicas: 2
  selector:
    app: apache
  template:
    metadata:
      name: apache-pod
      labels:
        app: apache
        version: latest
    spec:
      containers:
        - name: apache-container
          image: httpd:latest
          livenessProbe:
            initialDelaySeconds: 5
          ports:
            - containerPort: 80
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: replicacontroller-svc
spec:
  type: NodePort
  selector:
    app: apache
  ports:
    - port: 8080
      nodePort: 30002
      targetPort: 80
---

