---
apiVersion: v1
kind: ReplicationController
metadata:
  name: replica-1
  labels:
    app: apache
    version: latest
spec:
  minReadySeconds: 2 # bydefault value '0'
  replicas: 2
  selector:
    app: apache
  template:
    metadata:
      name: apache_pod
      labels:
        app: apache
        version: latest
      spec:
        containers:
          - name: apache_container
            image: apache:latest
            livenessProbe:
              initialDelaySeconds: 5
            ports:
              - containerPort: 80
                protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: replicacontroller_svc
spec:
  type: NodePort 
  selector: 
    app: apache 
  ports: 
    - port: 30002
      nodePort: 8080
      targetPort: 80
--- 