---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replica-set
  labels:
    app: replica-apache
    version: "1.0"
spec:
  minReadySeconds: 3
  replicas: 2
  selector:
    matchLabels:
      app: replica-apache
      version: "1.0"
  template:
    metadata:
      name: apachepod
      labels:
        app: replica-apache
        version: "1.0"
    spec:
      containers:
        - name: apachecontainer
          image: httpd:latest
          ports:
            - containerPort: 80
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: replicaset-svc
spec:
  type: NodePort 
  selector: 
    app: replica-apache 
  ports: 
    - port: 8080
      nodePort: 30001
      targetPort: 80
---