---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replica_set
  labels:
    app: replica_apache
    version: 1.0
spec:
  minReadySeconds: 3
  replicas: 2
  selector:
    matchLabels:
      app: replica_apache
      version: 1.0
  template:
    metadata:
      name: apachepod
      labels:
        app: replica_apache
        version: 1.0
    spec:
      containers:
        - name: apachecontainer
          image: apache:latest
          ports:
            - containerPort: 80
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: replicaset_svc
spec:
  type: NodePort 
  selector: 
    app: replica_apache 
  ports: 
    - port: 30001
      nodePort: 8080
      targetPort: 80
---