apiVersion: v1
kind: Pod
metadata:
  name: init-container
spec:
  initContainers:
    - name: init-cont1
      image: alpine:latest
      command:
        - sleep
        - "30"
    - name: init-cont2
      image: tomcat:latest
      command:
        - sleep
        - "30"
  containers:
    - name: container1
      image: nginx:latest
      ports:
        - containerPort: 80
          protocol: TCP
